import {
  AUTH_USERS_EMAIL_MAX_LENGTH,
  AUTH_USERS_FIRST_NAME_MAX_LENGTH,
  AUTH_USERS_LAST_NAME_MAX_LENGTH,
  AUTH_USERS_MIDDLE_NAME_MAX_LENGTH,
  AUTH_USERS_PASSWORD_MAX_LENGTH,
  AUTH_USERS_PHONE_NUMBER_MAX_LENGTH,
  AUTH_USERS_USERNAME_MAX_LENGTH,
} from '@js-modules/api-nest-module-auth-basic';

export const USERS_USERNAME_MAX_LENGTH = AUTH_USERS_USERNAME_MAX_LENGTH;
export const USERS_EMAIL_MAX_LENGTH = AUTH_USERS_EMAIL_MAX_LENGTH;
export const USERS_PHONE_NUMBER_MAX_LENGTH = AUTH_USERS_PHONE_NUMBER_MAX_LENGTH;
export const USERS_PASSWORD_MAX_LENGTH = AUTH_USERS_PASSWORD_MAX_LENGTH;
export const USERS_FIRST_NAME_MAX_LENGTH = AUTH_USERS_FIRST_NAME_MAX_LENGTH;
export const USERS_MIDDLE_NAME_MAX_LENGTH = AUTH_USERS_MIDDLE_NAME_MAX_LENGTH;
export const USERS_LAST_NAME_MAX_LENGTH = AUTH_USERS_LAST_NAME_MAX_LENGTH;
