export const AUTH_USERS_SERVICE = Symbol('AUTH_USERS_SERVICE');

export const AUTH_USERS_USERNAME_MAX_LENGTH = 64;
export const AUTH_USERS_EMAIL_MAX_LENGTH = 128;
export const AUTH_USERS_PHONE_NUMBER_MAX_LENGTH = 64;
export const AUTH_USERS_PASSWORD_MAX_LENGTH = 128;
export const AUTH_USERS_FIRST_NAME_MAX_LENGTH = 64;
export const AUTH_USERS_MIDDLE_NAME_MAX_LENGTH = 64;
export const AUTH_USERS_LAST_NAME_MAX_LENGTH = 64;
