export const KEYCLOAK_ADMIN_CLIENT = 'KEYCLOAK_ADMIN_CLIENT';
export const KEYCLOAK_ADMIN_CLIENT_CONFIG = 'KEYCLOAK_ADMIN_CLIENT_CONFIG';
export const KEYCLOAK_MULTI_ISSUER_CONFIG = 'KEYCLOAK_MULTI_ISSUER_CONFIG';
