import {
  AUTH_USERS_EMAIL_MAX_LENGTH,
  AUTH_USERS_PASSWORD_MAX_LENGTH,
  AUTH_USERS_PHONE_NUMBER_MAX_LENGTH,
  AUTH_USERS_USERNAME_MAX_LENGTH,
} from '../../../../api-nest-utils/src';

export const USERS_USERNAME_MAX_LENGTH = AUTH_USERS_USERNAME_MAX_LENGTH;
export const USERS_EMAIL_MAX_LENGTH = AUTH_USERS_EMAIL_MAX_LENGTH;
export const USERS_PHONE_NUMBER_MAX_LENGTH = AUTH_USERS_PHONE_NUMBER_MAX_LENGTH;
export const USERS_PASSWORD_MAX_LENGTH = AUTH_USERS_PASSWORD_MAX_LENGTH;
