export const NAV_DRAWER_WIDTH_EXPANDED_SPACING = 42;
export const NAV_DRAWER_WIDTH_COLLAPSED_SPACING = 13.5;

export const WORKSPACE_TOOLBAR_PADDING_TOP_SPACING = 0.5;
export const WORKSPACE_TOOLBAR_PADDING_BOTTOM_SPACING = 2;
export const WORKSPACE_PADDING_X_SPACING = 5;
