export const AUTH_PROTOCOL_TRAVEL_LOG = 'http';
export const AUTH_IP_TRAVEL_LOG = 'localhost';
export const AUTH_HOST_TRAVEL_LOG = `${AUTH_PROTOCOL_TRAVEL_LOG}://${AUTH_IP_TRAVEL_LOG}`;
export const AUTH_PORT_TRAVEL_LOG = '8080';
export const AUTH_URI_TRAVEL_LOG = `${AUTH_HOST_TRAVEL_LOG}:${AUTH_PORT_TRAVEL_LOG}`;

export const WEB_CLIENT_PROTOCOL_TRAVEL_LOG = 'http';
export const WEB_CLIENT_IP_TRAVEL_LOG = 'localhost';
export const WEB_CLIENT_HOST_TRAVEL_LOG = `${WEB_CLIENT_PROTOCOL_TRAVEL_LOG}://${WEB_CLIENT_IP_TRAVEL_LOG}`;
export const WEB_CLIENT_PORT_TRAVEL_LOG = '5173';
export const WEB_CLIENT_URI_TRAVEL_LOG = `${WEB_CLIENT_HOST_TRAVEL_LOG}:${WEB_CLIENT_PORT_TRAVEL_LOG}`;

export const API_CORE_PROTOCOL_TRAVEL_LOG = WEB_CLIENT_PROTOCOL_TRAVEL_LOG;
export const API_CORE_IP_TRAVEL_LOG = WEB_CLIENT_IP_TRAVEL_LOG;
export const API_CORE_HOST_TRAVEL_LOG = `${API_CORE_PROTOCOL_TRAVEL_LOG}://${API_CORE_IP_TRAVEL_LOG}`;
export const API_CORE_PORT_TRAVEL_LOG = '3000';
export const API_CORE_URI_TRAVEL_LOG = `${API_CORE_HOST_TRAVEL_LOG}:${API_CORE_PORT_TRAVEL_LOG}`;
